import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useEffect, useRef, useState } from 'react';

export default function Home() {
  const [result, setResult] = useState('');
  const apiURL = useRef('');

  function getResult() {
    fetch(apiURL.current)
      .then((res) => res.json())
      .then((res) => {
        setResult(res.data);
      });
  }

  useEffect(() => {
    const isTauri = (window as any).__TAURI__;
    apiURL.current = isTauri ? 'http://localhost:5661/add' : '/api/add';
    if (isTauri) {
      import('@tauri-apps/api/shell').then((mod) => {
        const command = mod.Command.sidecar('bin/server');
        command.execute();
      });
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div className={styles.result}>
            <p>Hello {(window as any).__TAURI__ ? 'from tauri' : 'from web'}</p>
            <div>
              <button className={styles.button} onClick={() => getResult()}>
                Click me to get result from server
              </button>
              {result ? (
                <div>
                  <p>Result from server:</p>
                  <p>{result}</p>
                </div>
              ) : null}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
